# Generated by Django 4.0.6 on 2022-11-13 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_authorprofile_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorprofile',
            name='skype_url',
        ),
        migrations.RemoveField(
            model_name='authorprofile',
            name='twitter_url',
        ),
    ]
